public enum EnumMoveDirection {
    FORWARD,
    BACKWARDS,
    ROTATE_YAW_POS,
    ROTATE_YAW_NEG,
    ROTATE_PITCH_POS,
    ROTATE_PITCH_NEG,
    ROTATE_ROLL_POS,
    ROTATE_ROLL_NEG,
    STRAFE_LEFT,
    STRAFE_RIGHT,
    RAISE,
    LOWER,
    RAISE_LOWER,
    STABILISE,
    NONE
}